### PR TITLE
fix(html pipe): pipeline v6.10.0 breaks some project deployments

### LINKED ISSUE #642: Pipeline v6.10.0 breaks some project deployments
Appeared via the helix-pages integration tests: https://github.com/adobe/helix-pages/pull/212

Deployed helix-page project fires an 500 for each page request.

Initial debugging session reveal runtime execution error: 

```
"error": "Initialization has failed due to: Error: Cannot find module './utils/common'\n    at webpackEmptyContext (/nodejsAction/XXEKhcLL/html.js:273252:10)\n    at /nodejsAction/XXEKhcLL/html.js:272965:14\n    at define (/nodejsAction/XXEKhcLL/html.js:272958:20)\n    at Object.<anonymous> (/nodejsAction/XXEKhcLL/html.js:272962:1)\n    at Object.Array.concat.webpackEmptyContext.keys (/nodejsAction/XXEKhcLL/html.js:273245:30)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)\n    at Object.Array.concat.define (/nodejsAction/XXEKhcLL/html.js:272802:16)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)\n    at Object.Array.concat.setdefault.setdefault (/nodejsAction/XXEKhcLL/html.js:224335:37)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)"
```

This seems to come from newly added npm dependency `emmet`: https://github.com/emmetio/emmet/blob/v1.6.3/lib/emmet.js#L10

`emmet` does not seem to be webpack friendly: https://github.com/emmetio/emmet/issues/516

Recommandation is to use https://www.npmjs.com/package/@emmetio/expand-abbreviation instead. Based on @ramboz, this is all we need anyway.

### PR DESCRIPTION
**Pull request by ramboz**
Emmet is triggering webpack packaging issues and should be replaced by a more lightweight solution

fix #642

### CODE REVIEW

**Comment by tripodsan** [comment]
@ramboz any update on this?

**Comment by ramboz** [comment]
@tripodsan Didn't manage to fix the tests yesterday, picking this up today.
Having access to project-helix (private) repo would help verifying I have everything properly set up. Since I missed those the 1st time, I want to make sure I'm running the proper setup

**Comment by trieloff** [comment]
@ramboz I just sent you the invite to `adobe-private`

**Comment by kptdobe** [comment]
Tests are green with updated helix-cli. See https://github.com/adobe/helix-cli/issues/1353

**Comment by kptdobe** [comment]
Back to green!!
I had to fix the ci multiple times (we were not running the tests with the helix-pipeline branch being PR), fix the cli (the changes introduced some new requests, tests needed to be adapted) and re-run the tests here.
We should be good to go!

**Pull request merged**
