### PR TITLE
fix(icons): use title from SVG file

### LINKED ISSUE #527: [icons] use <title> tag from SVG file
Currently, we write:
```html
<svg class="icon icon-twitter">
    <use xlink:href="/icons/bla.svg">
        <title>bla</title>
    </use>
</svg>
```
Instead, it should be:
```html
```html
<svg class="icon icon-twitter">
    <use xlink:href="/icons/bla.svg"></use>
</svg>
```
since the `<title>` tag should come from the SVG symbol in the referenced file.

See also https://css-tricks.com/svg-symbol-good-choice-icons/#article-header-id-1

### PR DESCRIPTION
**Pull request by rofe**
Fix #527

### CODE REVIEW

**Comment by rofe** [comment]
I can see the `<title>` tag in the shadow DOM when inspecting the element, but the browser doesn't display any tool tip unfortunately...

**Comment by rofe** [comment]
@davidnuescheler @trieloff wdyt?

**Comment by trieloff** [comment]
https://css-tricks.com/accessible-svgs/ (scroll to "Inline SVG") has some suggestions for working around the browser bugs.

**Comment by rofe** [comment]
Thanks for the pointer. However I don't think we want to inline SVG, do we? We could, using the same ESI trick we use for other statics... 

I explicitly decided against adding `aria-*` and `role` attributes because I think we should tackle this holistically in #522.

**Pull request merged**
