### PR TITLE
feat(log): use helix-log instead of winston

### PR DESCRIPTION
**Pull request by tripodsan**
- uses openwhisk-action-utils to setup logging (gives coralogix support)
- uses helix-log under the hood
- winston log interface compatible
- removed default file logger of 'logs/pipeline.log'.

### CODE REVIEW

**Comment by tripodsan** [comment]
there is still one test failing using `nock` when executing all tests at once. executing the test itself works.
I'll need some more time to fix that, but if you could already review the changes, that would be great.

**Comment by kptdobe** [comment]
Smoke tests also fail: https://circleci.com/workflow-run/2535ca55-f1a5-4a0b-8f04-eeef0de0a28f
Plenty of `[hlx] error: [object Object]` while running a project.

**Comment by kptdobe** [comment]
Ah I think the pb of the smoke tests is coming from the simulator which also need to be migrated.

**Comment by kptdobe** [comment]
Please test the changes in "production" because I tried and I still do not get Coralogix logs. But this might be due to my config / setup... like Coralogix key missing in my namespace... I am investigating but for now, cannot find an explanation.

**Comment by kptdobe** [comment]
Just tested and no pipeline logs is sent to Coralogix.

**Comment by tripodsan** [comment]
> Just tested and no pipeline logs is sent to Coralogix.

and if you test locally? i.e. executing the `html.bundle.js` ?

**Comment by kptdobe** [comment]
humm... I can still find some `winston` references in that `html.bundle.js`. Need to investigate further.

**Comment by kptdobe** [comment]
ok, found why I did not have the latest version (my project had set a dependency to older helix-pipeline). But with latest code, still no logs in Coralogix.

**Comment by tripodsan** [comment]
> humm... I can still find some `winston` references in that `html.bundle.js`. Need to investigate further.

yes. they come from helix-shared...

**Comment by tripodsan** [comment]
> ok, found why I did not have the latest version (my project had set a dependency to older helix-pipeline). But with latest code, still no logs in Coralogix.

what happens if you execute the bundle locally. with the node REPL ?

**Comment by kptdobe** [comment]
How do I do this ?

**Comment by tripodsan** [comment]
```
$ hlx package
$ node -p "require('./.hlx/build/src/html.bundle.js').main({CORALOGIX_API_KEY:'sdf'}).then(console.log).catch(console.error)"
```

**Comment by kptdobe** [comment]
Works!

For the record: 

My deployed action was not logging anything to Coralogix because the `CORALOGIX_API_KEY` was missing during the deployment:
```
hlx deploy --default CORALOGIX_API_KEY XXXX
```
fixed the issue.

Thanks.

**Pull request merged**
