### PR TITLE
fix(all pipe): reduce schema validation error reporting

### LINKED ISSUE #92: Schema validation - disable for now
The schema validation is a really annoying feature : for every single new non-handled case, the rendering the broken. 

New one: 
```
[hlx] warn: tapping failed: Error: Invalid Context at step 2
data.content.mdast.children[9].meta should be string undefined, data.content.mdast.children[11].meta should be string undefined, data.content.mdast.children[13].meta should be string undefined, data.content.mdast.children[15].meta should be string undefined
```
Multiple issues:

1. The logs are `warn` while the validation blocks the rendering. They should be `error`.
2. Appart from adding a break point at the right place in the pipeline (for the record, this line https://github.com/adobe/hypermedia-pipeline/blob/master/src/utils/validate.js#L46), impossible to know what is wrong
3. To unblock the rendering, you need to patch the current hlx version

My proposal here is to keep the messages as `warnings` and to disable the "blocking" aspect of the validation. 

cc @trieloff

### PR DESCRIPTION
**Pull request by ramboz**
fix #92

### CODE REVIEW

**Comment by trieloff** [comment]
Ha. I haven't seen @tripodsan's comment, but it looks like we think alike.

**Comment by tripodsan** [comment]
@ramboz do you plan on working on this?

**Comment by ramboz** [comment]
@tripodsan Somehow missed the comments it seems. I'll pick it up tomorrow

**Comment by ramboz** [comment]
@trieloff, @tripodsan: didn't know about that property. Definitely cleaner!

**Comment by trieloff** [comment]
Not sure why the smoke tests are failing: https://circleci.com/gh/adobe/helix-pipeline/3496?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by ramboz** [comment]
Not sure either…
Difference is that I get this in the markup:
```html
<div class="embed  embed-has-title">
  <span class="title">Fastly error: unknown domain embeds.project-helix.io</span>
<div>
```

Could this be a flaky failure just at that time?

**Comment by trieloff** [comment]
I think it's fine to update the smoke tests and then merge.

**Pull request merged**
