### PR TITLE
fix(pipe): adjust blob images on vdom

### LINKED ISSUE #990: Image Rewriter does not work for HTML images in Markdown
See: https://spark-website--adobe.hlx.page/marketing/video-maker.md

```markdown

![](https://hlx.blob.core.windows.net/external/4983dfb7eee36d6c89487cb127b75d88de073955#image.png)

# Create Videos for Free in Minutes

## Add footage, music, photos, and more to create a captivating video. No editing skills needed.

[Add music to your video now](https://adobesparkvideo.app.link/NdKoobyZJ5)

---



## Free online video maker with music and pictures

Create compelling video content with ease! Piece together your footage with photos, music, voiceovers, and beautiful transitions from one scene to the next.

| Template List Large                                                                                                                                                                                                               |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <p><img src="https://hlx.blob.core.windows.net/external/ad9bf93ad8c7dc9f830b1d54ae7888fa52a99a17#image.png" alt=""></p><p><a href="https://adobesparkpost.app.link/doId8gECEX">https://adobesparkpost.app.link/doId8gECEX</a></p> |

[Create your video now](https://adobesparkvideo.app.link/NdKoobyZJ5)

## How to Make Your Own Video

| How-to Steps                                               |                                                                                                                                                                                                                                                                                                                                                                                                            |
| ---------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Start by creating a new project with Spark Video App       | Clicking the big plus button on web or in the iOS app will open a slide-based editor. No complicated timelines here with Spark video's intro maker! We suggest storyboarding out your video story within the app by selecting one of the preloaded story structures or creating your own by adding notes to slides, which will guide your creation. Each slide should represent just one point or thought. |
| Add media to the slides                                    | Now it’s time to add media to your slides. Choose between images, video clips, icons, or text. You can search for free photos or icons within the tool or use your own images or video clips. Add up to 30 seconds of video at a time to each slide. We recommend using short video clips or images to visually represent your message.                                                                    |
| Select pre-designed layouts                                | Present your media in a variety of layouts by selecting one of the preloaded placements in the top left corner labeled “layouts.”                                                                                                                                                                                                                                                                          |
| Use text to communicate key information or calls to action | Text on screen makes sure those watching your video without the sound turned on get your full message. If you’d like to speak directly to your audience, simply record your voice by hitting the red button and speaking into your phone or computer.                                                                                                                                                      |
| Spice it up with a theme and soundtrack                    | Spark Video comes pre-loaded with themes that control the overall look and feel of your video. Themes power transitions between slides and the motion of elements. Simply tap the “Themes” category and choose from unique themes. You can also add music by uploading your own track or selecting one of the free songs in Spark Video.                                                                   |
| Publish and share                                          | Once you’ve finished your video, it’s ready to share! Save your video directly to your device, or copy the link to share it over the web. Post your video to your social media pages, YouTube channels, or blog, or simply text or email it to your favorite person. Adobe Spark makes it easy to showcase your creations in whatever medium you desire!                                                   |

[Create your video now](https://adobesparkvideo.app.link/NdKoobyZJ5)

## Customize your video to make it your own

Adobe Spark comes fully loaded with several customization options — ensuring your video is as unique as it is engaging. Make changes to music, images, text and the layout of your video with a click of your mouse. This powerful online video maker allows you to make as many changes as you like, so you can truly make your imagination come to life. Make a video with Adobe Spark, and you’ll never have to worry about it looking like all the rest.



Using Adobe Spark as a free video maker simply couldn’t be easier. After selecting the “Video” option from the main menu, you’ll be taken to a title screen — where you can give your video project a title. Enter some text, or skip this stage and head straight to the design interface. Don’t worry if you want to change the title later, as you can make unlimited changes to text. You then get the opportunity to choose a video template or start the design process from scratch.

## Why use Spark's online video maker?

Professional video production services are never cheap, and they don’t always connect with the source material. By using Adobe Spark to make videos online, you can stay in charge of the creative process without breaking the bank. And you won’t need a degree in video production, as the design interface is simple, visual and highly responsive.



Make sure your online videos stand out from all the rest by creating them with Adobe Spark.

## More Spark video examples

| Linked Image                                                                                                                                                                                                                        |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <p><img src="https://hlx.blob.core.windows.net/external/35ddae1c71c67d8605c37871b8881af5d29c6acc#image.png" alt=""></p><p><a href="https://spark.adobe.com/video/FZXqFDNFog5qY">https://spark.adobe.com/video/FZXqFDNFog5qY</a></p> |

```

The image rewriter will rewrite `![](https://hlx.blob.core.windows.net/external/4983dfb7eee36d6c89487cb127b75d88de073955#image.png)` but ignore `<img src="https://hlx.blob.core.windows.net/external/35ddae1c71c67d8605c37871b8881af5d29c6acc#image.png" alt="">` and `<img src="https://hlx.blob.core.windows.net/external/ad9bf93ad8c7dc9f830b1d54ae7888fa52a99a17#image.png" alt="">` because the latter two are part of the HTML, but not proper MDAST nodes.

https://github.com/adobe/helix-pipeline/blob/7f533a83eed348150d51d3600e29530845cec512/src/html/rewrite-blob-images.js#L24-L25

We can fix this by either scanning for HTML in MDAST or adding a second rewriter that operates on the DOM.

@tripodsan I'd count this issue as a point against lazy block tables and for proper directive blocks.

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #990

BREAKING CHANGE: rewriteBlobImages() now operates on the document and no longer on mdast.

- includes https://github.com/adobe/helix-pipeline/pull/960
---

**NOTE**: this branch is currently used by the helix pages https://github.com/adobe/helix-pages/pull/662

### CODE REVIEW

**Review by trieloff — APPROVED** [review]
Looks good, but is a breaking change for anyone (no one I know) using `rewriteBlobImages` in a custom pipeline.

**Comment by tripodsan** [comment]
> Looks good, but is a breaking change for anyone (no one I know) using `rewriteBlobImages` in a custom pipeline.

ok, I'll make it breaking....

**Comment by tripodsan** [comment]
@trieloff should I merge the changes from https://github.com/adobe/helix-pipeline/pull/960/files also here ?

**Comment by trieloff** [comment]
Yes

**Review by rofe — APPROVED** [review]

**Comment by trieloff** [comment]
https://github.com/adobe/helix-home/issues/183#issuecomment-797561083

We need to roll back the `/icons/` changes.

**Comment by trieloff** [comment]
Reverted the icon changes.

**Pull request merged**
