### PR TITLE
refactor(html pipe): use helix-fetch to fetch the markdown files 

### PR DESCRIPTION
**Pull request by ramboz**
Extract helix-fetch changes from #533:
- Use helix-fetch instead of request promise to fetch the markdown file
- Prepare structure to support fetch several files in parallel when we fetch the markdown file (fstab, markup config, etc.)
- Adjust tests

### CODE REVIEW

**Comment by trieloff** [comment]
> ps: let's wait after next tuesday before we replace the client

we could just hold back the helix-pipeline update in helix-pages, which has the same effect.

**Comment by ramboz** [comment]
@tripodsan It does support the request `timeout` which is the only use case we had with the promise request as far as I know.

**Comment by ramboz** [comment]
@tripodsan I tested both locally via:
```zsh
HLX_CUSTOM_PIPELINE=https://github.com/adobe/helix-pipeline.git#fetch hlx up
```

and in the I/O runtime via:

`.env`
```
HLX_CUSTOM_PIPELINE=https://github.com/adobe/helix-pipeline.git#fetch
```

Is there another test you'd like me to perform?

**Comment by tripodsan** [comment]
> Is there another test you'd like me to perform?

does:
```
HLX_CUSTOM_PIPELINE=https://github.com/adobe/helix-pipeline.git#fetch
```

use that specific pipeline when deploying the action? I didn't know... if so, yes. then ok.

**Comment by ramboz** [comment]
@tripodsan I think so. This is what I got when running `hlx deploy --add=default`:
```
Module @adobe/helix-pipeline not found.
Running npm install https://github.com/adobe/helix-pipeline.git#fetch in .hlx/build ...
+ @adobe/helix-pipeline@6.2.3
added 243 packages from 292 contributors in 4.75s
Using @adobe/helix-pipeline version 6.2.3 from .hlx/build/node_modules/@adobe/helix-pipeline.
html (src/html.htl)
[==================================================] packaging html.js 4.3s
✅  packaging completed
[==================================================]  0.0s


✅  deployment of 1 action completed:
   - ramboz/ff8594ad0112ddf2c23a141fbf1a55f778cee169/html (2.74 MiB)
Affected strains of ssh://git@github.com/ramboz/hlx-demo.git#master:
- default
Updated helix-config.yaml
```
It seems to be using `#fetch` branch

**Pull request merged**
