### PR TITLE
Update ReadMe

### PR DESCRIPTION
**Pull request by saritchie**
Improved 'Error Handlers' paragraph for clarity and concision. Hope this helps!

### CODE REVIEW

**Comment by trieloff** [comment]
@saritchie thanks for the PR. In order to accept this, we need the signed Adobe CLA, which you can sign here: http://opensource.adobe.com/cla.html

**Comment by saritchie** [comment]
Just signed the CLA!

**Comment by trieloff** [comment]
Thank you, it's merged now.

**Pull request merged**
